import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.dirname(here),out=path.join(here,'build');
fs.mkdirSync(out,{recursive:true});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const offices=JSON.parse(read('config.local.json')),emails=JSON.parse(read('gas/access.local.json'));
if(!emails.length||emails.some(e=>typeof e!=='string'||!e.includes('@')))throw Error('許可アカウントが未設定です。');
fs.writeFileSync(path.join(out,'Config.gs'),'const OFFICES='+JSON.stringify(offices)+';\nconst ALLOWED_EMAILS='+JSON.stringify(emails)+';\n');
const source=read('production.mjs');
let aggregate=source.slice(source.indexOf('export function validDate'),source.indexOf('export async function readProduction'))+source.slice(source.indexOf('export function aggregateProduction'),source.indexOf('export function createProductionService'));
for(const name of ['validDate','normalizeReports','aggregateProduction'])aggregate=aggregate.replaceAll(name,name+'_');
aggregate=aggregate.replaceAll('export function','function').replace("createHash('sha256').update(p.name).digest('hex').slice(0,20)",'personKey_(p.name)');
fs.writeFileSync(path.join(out,'Aggregate.gs'),aggregate);
for(const name of ['Code.gs','appsscript.json'])fs.copyFileSync(path.join(here,name),path.join(out,name));
let html=read('index.html').replace('<head>','<head><base target="_top">');
for(const name of ['style.css','production.css'])html=html.replace(`<link rel="stylesheet" href="./${name}">`,()=>`<style>${read(name)}</style>`);
html=html.replace('<script type="module" src="./production.js"></script>',()=>'<script type="module">\ntry {\n'+read('gas/transport.js')+'\n'+read('production.js')+'\n} catch(e) { document.querySelector("#prodError").textContent="ログインまたはデータ取得に失敗しました。ページを開き直してください。"; }\n</script>');
fs.writeFileSync(path.join(out,'Index.html'),html);
console.log('Built private Apps Script deployment files.');
